### ISSUE TITLE
Wrong deserialization when expected property type is object

### ISSUE THREAD

**Issue by colderlord** [bridgedotnet/Bridge.Newtonsoft.Json#101]
Example [Deck.Net](https://deck.net/dc8f2b0e3c6e6c76aab16ec44903aa05)

**Comment by fabriciomurta** [comment]
Thanks for reporting the issue, we've just fixed and merged it upstream!

The fix will be available next Bridge.Newtonsoft.Json release, which should follow Bridge's as well.
