### ISSUE TITLE
DateTimeOffset deserialization fails from different time zone to deck server

### ISSUE THREAD

**Issue by FasettoAndrew** [bridgedotnet/Bridge.Newtonsoft.Json#105]
When I serialize and deserialize a new DateTimeOffset object on deck.net, I get the following error: `Argument_OffsetPrecision, Parameter name: offset`

I am working in the UK so my timezone is set to BST which is UTC +1 hour.

You can view the deck here:
https://deck.net/ba083a00c886571deec195adc6497b53

And the screenshot of the issue i'm experiencing if your timezone does not match mine and does not recreate issue:
![image](https://user-images.githubusercontent.com/13521143/39571145-759409ec-4ec2-11e8-956f-300a8ccbfff4.png)

Originally reported here:
https://github.com/bridgedotnet/Bridge.Newtonsoft.Json/issues/89

**Comment by FasettoAndrew** [comment]
Sometimes I also get a 
`Argument_UTCOutOfRange`
exception as well from the same code.

see the below screenshot:
![image](https://user-images.githubusercontent.com/13521143/39571309-f572abe6-4ec2-11e8-99d5-3e1f32d60c69.png)

**Comment by fabriciomurta** [comment]
Can you share what your *serialized* string look like? Just a `Console.WriteLine(serialized);` should do.

I'm getting `"0001-01-01T00:00:00-02:00"` and all runs nicely. This could be any regional separator settings too.

**Comment by FasettoAndrew** [comment]
My serialized string comes out as:

`"0001-01-01T00:00:00+00:00"`

**Comment by fabriciomurta** [comment]
Interesting, I still can deserialize it if I type in the strings themselves:
https://deck.net/7c2c4667aa3779eab363531c1db6cdfc

What browser and version are you using?

**Comment by FasettoAndrew** [comment]
I am using Firefox developer version 61.0b2 (64-bit)

**Comment by fabriciomurta** [comment]
I've just tried with firefox here (vanilla consumer version). It seems it is only available version 59. 59.0.3, 64-bit also.

Thanks for the details, that must be indeed be a time zone-specific issue.

**Comment by FasettoAndrew** [comment]
Is there any ETA for a fix for this issue? We have been waiting for DateTimeOffset support in Bridge.Net and it seems this issue is the final hurdle before we can fully use it.

**Comment by geoffreymcgill** [comment]
We are working on the issue and anticipate having a fix available for the upcoming 17.1.0 release.

**Comment by fabriciomurta** [comment]
The fix has just been merged upstream and will be available next Bridge release. Notice the fix here was applied to Bridge sources, not Bridge.Newtonsoft.Json package, so the version this fix is going to make it to is Bridge 17.1.0 and not necessarily Bridge.Newtonsoft.Json 1.7.1 (as currently pointed by the milestone).

**Comment by fabriciomurta** [comment]
We've just updated our development deck to include the changes implied by the fix of this issue. So if you're looking forward to testing this, please give it a try! https://dev.deck.net/ba083a00c886571deec195adc6497b53 (notice the 'dev.' to the beginning of the url)
