### ISSUE TITLE
Add ISerializationBinder

### ISSUE THREAD

**Issue by colderlord** [bridgedotnet/Bridge.Newtonsoft.Json#106]
Please add interface `ISerializationBinder`
[Documentation](https://www.newtonsoft.com/json/help/html/T_Newtonsoft_Json_Serialization_ISerializationBinder.htm)

**Comment by fabriciomurta** [comment]
Implemented! @vladsch sent his own implementation of the interface, so we can assume this as closed. The fix will go to the next release (see assigned milestone).
