### ISSUE TITLE
JsonConvert.DeserializeObject calls non default constructor

### ISSUE THREAD

**Issue by kcudnik** [bridgedotnet/Bridge.Newtonsoft.Json#107]
JsonConvert.DeserializeObject calls non default constructor.

Not sure whether this is a feature or a bug, but i would expect that when there is no default constructor ether deserialization should fail or none of the constructors should be called. Current scenario adds "null" to the list since non default constructor is called with default parameters which for string is null. Or maybe list should be entirely replaced in that scenario instead of merge ?

### Steps To Reproduce

https://deck.net/c3b12c197292f2c81e72c4b4782044f1

```csharp
public class B
{
    public B(string foo)
    {
        Console.WriteLine("ctr: {0}", foo ?? "null");
        
        list = new List<string>{foo};
    }
    
    public List<string> list;
}

public class Program
{
    public static void Main()
    {
        var b = new B("foo");
        
        b.list.Add("baz");
       
        string s = JsonConvert.SerializeObject(b);

        Console.WriteLine(s);

        var bb = JsonConvert.DeserializeObject<B>(s);
        
        foreach(var item in bb.list)
        {
            // null is on list
            Console.WriteLine("{0}", item ?? "null");
        }            
    }
}
```

### Expected Result

```js
ctr: foo
{"list":["foo","baz"]}
foo
baz
```

### Actual Result

```js
ctr: foo
{"list":["foo","baz"]}
ctr: null
null
foo
baz
```

**Comment by vladsch** [comment]
"B" class has only one constructor, therefore, we cannot run any other. So, deserializer calls the constructor with argument "null" (string default value). It is correct (the same behavior in original Newtonsoft.Json). The problem that Bridge deserializer merges list instead of replacing.

Expected result is
```
ctr: foo
{"list":["foo","baz"]}
ctr: null
foo
baz
```

The PR with the fix is created

**Comment by fabriciomurta** [comment]
The submitted fix by Vladimir looks great, we're confident it will fix this issue for good. It has been merged upstream and will make it to the next public Bridge.Newtonsoft.Json release (see attached milestone).

Thanks for reporting us the issue!

**Comment by kcudnik** [comment]
thanks!
