### ISSUE TITLE
Error deserializing to interface collections

### ISSUE THREAD

**Issue by fabriciomurta** [bridgedotnet/Bridge.Newtonsoft.Json#111]
Bridge.Newtonsoft.Json is unable to deserialize back a serialized structure defined like this:

```csharp
    public class Node
    {
        public string Name;
        public ICollection<Node> Children;
    }

    public class Response
    {
        public ICollection<Node> Nodes;
    }
```

If the `ICollection` references are changed to List, for example, then it works.

Deck reproducing the issue: https://deck.net/1ae56be36937c95938b13d351247f6bd
Equivalent Dotnet fiddle: https://dotnetfiddle.net/uNVb5N

See also: [ICollection not working or throws an exception](https://forums.bridge.net/forum/community/help/5455)

**Comment by ChrML** [comment]
I've also noticed this. Also applies to custom collection, list and dictionary types that implements IList or IDictionary and thus should work.

Temporary workaround is to provide a read-only accessor as type IList or IDictionary. Mark the original collection property with [JsonIgnore] just in case.

**Comment by fabriciomurta** [comment]
Good news, the proposed fix works for the IList and IDictionary interfaces as well!

**Comment by fabriciomurta** [comment]
Fixed and merged! The fix will make it live the next Bridge.Newtonsoft.Json package release!
