### ISSUE TITLE
Wrong object deserialization when list initialized in ctor

### ISSUE THREAD

**Issue by colderlord** [bridgedotnet/Bridge.Newtonsoft.Json#114]
Here some example:
I have ctor in my class. In constroctor i initialize new list with my own property. When i try to deserialize my property is empty, but in constructor property should be filled.

Some one when fix bug #107 was add new condition in method `needReuse` - i think problem is here.

https://deck.net/620b9fb89de80b31f2cb24b19214192a

https://dotnetfiddle.net/tuJ2G8

```csharp
public class Program
{
    public static void Main()
    {
        
        var msg = new MyClass();
        var str = JsonConvert.SerializeObject(msg);
        Console.WriteLine(str);
        var obj = JsonConvert.DeserializeObject<MyClass>(str);
        Console.WriteLine(obj.Items.Parent); // should be "123"
    }
    
    public class MyClass
    {
        public MyClass()
        {
            Items = new MyList();
            Items.Parent = "123";
        }
        
        public MyList Items {get;set;}
    }
    
    public class MyList : List<string>
    {
        public string Parent {get;set;}
    }
}
```

**Comment by fabriciomurta** [comment]
Fixed and merged! The fix will make it live the next Bridge.Newtonsoft.Json package release!
