### ISSUE TITLE
Wrong case sensitivity.

### ISSUE THREAD

**Issue by hardhub** [bridgedotnet/Bridge.Newtonsoft.Json#14]
https://deck.net/41a741e6340da07afacab52836978a6e

Newtonsoft.Json tries case sensitive first... if not it performs case insensitive name matching.

Also it is not possible to derive from DefaultContractResolver or implement own IContractResolver.
So there is no way to override this behavior and convert from camel to pascal case.

It is result of browser native implementation. Possible solution:

_The optional reviver parameter is a function that will be called for every key and value at every level of the final result. Each value will be replaced by the result of the reviver function. This can be used to reform generic objects into instances of pseudoclasses, or to transform date strings into Date objects._

_The stringifier method can take an optional replacer function. It will be called after the toJSON method (if there is one) on each of the values in the structure. It will be passed each key and value as parameters, and this will be bound to object holding the key. The value returned will be stringified._

--
Also it looks it ignores Convention attribute... And I guess it is not correct...
In any case it does not allow me to make a workaround.

**Comment by geoffreymcgill** [comment]
We will be working on this issue to implement fallback casing support in **Bridge.Newtonsoft.Json**. 

The Reviver option is available by using the native JavaScript `JSON.Parse` method.

**Comment by geoffreymcgill** [comment]
The `[Convention]` attribute is not supported by **Newtonsoft.Json**, so we will not be able to support with **Bridge.Newtonsoft.Json**. 

We will be able to implement the fallback to case-insensitive match if the strong match is not found at first.
