### ISSUE TITLE
JsonConvert.DeserializeObject<bool>("True") throws JsonReaderException

### ISSUE THREAD

**Issue by olivermue** [bridgedotnet/Bridge.Newtonsoft.Json#150]
Tested with version 12.0.1 The following code throws:

https://deck.net/39d5bbedae2dc79bb76c03cb84d18d01

```
using System;
using Newtonsoft.Json;
					
public class Program
{
    public static void Main()
    {
        var result = JsonConvert.DeserializeObject<bool>("True");
        Console.WriteLine("Doesn't throw");
    }
}
```
Is this intended (and can we reconfigure the deserializer to allow this) or a bug?

And `"True".ToLowerInvariant()` is not an option.

**Comment by geoffreymcgill** [comment]
Thanks for the report. Obviously, this deserialization should be working and I'm surprised we don't have a test for this scenario already. We will investigate and fix the defect.

**Comment by fabriciomurta** [comment]
The overall behavior is corresponding to native Json: https://dotnetfiddle.net/833PS1

The only difference to Bridge, is the exact exception it throws (`Newtonsoft.Json.JsonReaderException` in native vs `Newtonsoft.Json.JsonException` in Bridge.

**Comment by olivermue** [comment]
Oh sorry, I just published the issue to the wrong project. I wanted to push that issue out to Newtonsoft, not to deck.net.

**Comment by fabriciomurta** [comment]
If you create the issue in the official newtonsoft repo, please link it here, in case it gets implemented in newtonsoft, we should follow. But I believe having it case-insensitive is achieved with serialization settings, or using custom serializers.
