### ISSUE TITLE
The .NET library supports deserializing from primitives to complex types via implicit or explicit operators but this version does not

### ISSUE THREAD

**Issue by ProductiveRage** [bridgedotnet/Bridge.Newtonsoft.Json#154]
I only realised today that the .NET version of this library supports implicit and explicit operators for some deserialization actions. I had previously thought that the only way to get seemingly-custom processing was via JsonConverters, which are know are not supported here. But the following works in .NET:

```
using System;
using Newtonsoft.Json;
					
public class Program
{
	public static void Main()
	{
		// AS the JSON has a string value but the "ID" property of Example is of type "SpecialID",
		// the explicit operator on the SpecialID class is used in the deserialisation process
		var json = "{ \"ID\": \"abc\" }";
		var value = JsonConvert.DeserializeObject<Example>(json);
		Console.WriteLine("ID: " + value.ID.Value);
	}
	
	private class Example
	{
		public SpecialID ID { get; set; }
	}
	
	private class SpecialID
	{
		public SpecialID(string value)
		{
			Value = value;
		}
		
		public string Value { get; set; }

		public static explicit operator SpecialID(string value)
		{
			return new SpecialID(value);
		}
	}
}
```

(see [https://dotnetfiddle.net/ov7oAR](https://dotnetfiddle.net/ov7oAR))

It doesn't work in Bridge, though - as per [https://deck.net/7084d9b41df525925377cc1909324866](https://deck.net/7084d9b41df525925377cc1909324866).

The support in the .NET library is limited because, as I understand it, it will only support calling implicit / explicit operators on the destination type if the source value is a primitive (because it might not have enough type information to determine whether there is a source type that has such an operator). It also can't support implicit / explicit operators if the source value is null because it can't know what type to look for as the argument on the operator.

I've raised this issue to document the case but I've got a pull request on the way that I think deals with it. I'm sure that it could do with some review, though, since it's been a while since I last looked at JsonConvert.js! I've got some "happy case" unit tests that would have failed before the change but which pass _with_ the change.

**Comment by fabriciomurta** [comment]
Hello ProductiveRage, sorry for no feedback since you posted this great report, along with the cool pull request! It was awesome and we're thrilled to add it to our next release! The pull request looks great and was just accepted and merged upstream.
