### ISSUE TITLE
Deserialize nullable objects invalid

### ISSUE THREAD

**Issue by angelsix** [bridgedotnet/Bridge.Newtonsoft.Json#18]
Comparing to the old `JSON.Parse`... `JsonConvert.Deserialize` loses nullable values on deserialization. It only works if you specify object literal

https://deck.net/63674400362dccdce1adef54826e830a

Also `JsonConvert.DeserializeObject<Test>(testJson, new JsonSerializerSettings { NullValueHandling = NullValueHandling.Include });` does not work which I would of expected that to be the fix

**Comment by angelsix** [comment]
And a stab in the dark your fix might need to start here 
https://github.com/bridgedotnet/Bridge.Newtonsoft.Json/blob/796f965d6b65dd26889dc44c801cb096821f4e97/Newtonsoft.Json/Resources/Manual/JsonConvert.js#L344

**Comment by angelsix** [comment]
Ok I've found a fix... well workaround in my eyes.

Deserialize to an object then use As...

var test = JsonConvert.DeserializeObject<System.Object>(testJson).As<Test>();

**Comment by angelsix** [comment]
Final update.

Add this to AssemblyInfo.cs
[assembly: Convention(Target = ConventionTarget.Member, Notation = Notation.LowerCamelCase)]

Now this will work:

var test = JsonConvert.DeserializeObject<System.Object>(json).As<T>();

So basically this code will work if you add the line to your AssemblyInfo.cs file
https://deck.net/b49755d09b242e16102ce5bfba2bd5f4

I would however expect a fix so that a DeserializeObject<T> works without needing to do DeserializeObject<object>().As<T>()...?

**Comment by geoffreymcgill** [comment]
Thanks for the report. I haven't had a chance to investigate exactly what's going wrong here, but just a few days ago there was a fix merged that included case-insensitive matching during deserialization. See Issue #14 ([pull request](https://github.com/bridgedotnet/Bridge.Newtonsoft.Json/pull/17))

The fix was merged into the **master** branch and will be included in the upcoming **16.0.0-rc** release. Maybe that fix will help with this scenario; at least it might mitigate the use of `[assembly: Convention]` attribute.

**Comment by angelsix** [comment]
Thanks I'll pull that once its released and confirm if it worked

**Comment by angelsix** [comment]
Just a heads up that my fix (DeserializeObject<object>().As<T>()... then causes List<x> deserialization to break.. now lists deserialize to arrays and so .Count doesn't work as it wants .length.

The work around to that is a load of ((dynamic)a).length calls but thats then getting into the realms of a lot of workarounds all through code.

Has the fix confirmed if it fixes this issue and any due date on this release?
