### ISSUE TITLE
NuGet metadata is incorrect/misleading

### ISSUE THREAD

**Issue by DanTup** [bridgedotnet/Bridge.Newtonsoft.Json#19]
On [NuGet](https://www.nuget.org/packages/Bridge.Newtonsoft.Json/) the package description is:

> A C# to JavaScript compiler. Write modern mobile and web apps in C#. Run them anywhere with JavaScript.

It also has the main Bridge repo url instead of this one.

**Comment by geoffreymcgill** [comment]
Thanks for the report. This old description was just an oversight that got copied along when we created the first .nuspec file for the project.

The **Bridge.Newtonsoft.Json** package description was updated last week and the new description will be available on [NuGet.org](https://www.nuget.org/packages/Bridge.Newtonsoft.Json/) with the next release.

## See Also

* https://github.com/bridgedotnet/Bridge.Newtonsoft.Json/commit/d01a2b0f2bb78b255f379ca4ca31918e8354240b
* https://forums.bridge.net/forum/community/help/4509-newtonsoft-json-detected?p=4523#post4523

**Comment by geoffreymcgill** [comment]
I need to review the two `Url` related properties again. Reopening...

**Comment by geoffreymcgill** [comment]
The [Newtonsoft.Json.nuspec](https://github.com/bridgedotnet/Bridge.Newtonsoft.Json/blob/master/.build/specs/Newtonsoft.Json.nuspec) file has been updated and will be deployed with the next public release.
