### ISSUE TITLE
Wrong enums serialization.

### ISSUE THREAD

**Issue by hardhub** [bridgedotnet/Bridge.Newtonsoft.Json#22]
Any ASP.NET Core web application by default serialize enums as integer.

So this controller code:

```C#
public enum TestEnum
    {
        Test1,
        Test2,
        Test3
    }

    public class TestObj
    {
        public int A { get; set; }
        public TestEnum B { get; set; }
    }

    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            TestObj obj = new TestObj();
            obj.A = 123;
            obj.B = TestEnum.Test3;

            return new JsonResult(obj);
        }
    }
	
```

outputs the following JSON:

```
JSON	
a	123
b	2
```

But **Bridge.Newtonsoft.Json** package works differently. 
`JsonConvert.SerializeObject(payload)` serializes enum as string.

Native `JSON.Stringify(payload)` works good (outputs integer).

So...
1) Is it bug? Wrong default config?
2) Can it be fixed by changing the default configuration of Bridge JSON lib?
3) What is better to use for now as workaround? Any custom configs? Or JSON.stringify?

**Comment by geoffreymcgill** [comment]
Looks like a defect. Just so we're all on the same page, can you share a [Deck](https://deck.net) which demonstrates the scenario?

**Comment by hardhub** [comment]
@geoffreymcgill 
I am not sure I can add JSON package to deck...
Or at least I do not know how do that.
Adding of Newtonsoft.Json namespace does not help.

**Comment by hardhub** [comment]
@geoffreymcgill 

Now it looks JSON is available...

https://deck.net/e1aab3fb5c601c792a732997df45ae84

"Size": "Small" should be "Size": 0

**Comment by geoffreymcgill** [comment]
Thanks for the sample. I was able to simplify your sample by removing the unrelated code, then reproduced the correct result at [DotNetFiddle](https://dotnetfiddle.net/G709Yx).

We will investigate and try to fix right away.
