### ISSUE TITLE
Deserialisation code mutates JsonSerializerSettings, causing further deserialisation to silently give the wrong results

### ISSUE THREAD

**Issue by DanTup** [bridgedotnet/Bridge.Newtonsoft.Json#25]
We found some of our objects were deserialising with empty collections hanging off them sometimes with no obvious pattern. The JSON was all correct and the types are fairly simple.

We stepped through the JS and found that when creating lists it was bailing out because the settings class has an `$list` property set (see [here](https://github.com/bridgedotnet/Bridge.Newtonsoft.Json/blob/594233f1b18e0b4b701b17a65705755c78a82e52/Newtonsoft.Json/Resources/Manual/JsonConvert.js#L493)). We added breakpoints and found that this property is being stitched onto the settings class as part of a previous deserialisation (though never removing it). We reuse the settings class inside our deserialiser to avoid needlessly creating new objects.

Here's a repo:

https://deck.net/1b9a997f3ce101185d6434578e913120/third

If you run this, you'll see it writes `1`. If you uncomment the deserialisation of json1 then it will start printing `0`.

**Comment by geoffreymcgill** [comment]
Hi @DanTup – Thanks for the excellent report. We will investigate right away.
