### ISSUE TITLE
Value type properties are not serialized properly

### ISSUE THREAD

**Issue by ddaspit** [bridgedotnet/Bridge.Newtonsoft.Json#27]
I encountered a regression in the recent Bridge.NET 16.1 release. When you call `JsonConvert.SerializeObject()` on an object that has a value type property, the property does not get serialized correctly. Adding the `ObjectLiteral` attribute to the class fixes the problem, so I believe it is related to changes in reflection in 16.1.

### Steps To Reproduce

https://deck.net/cc50624a20455f41d38591fca347902b

```c#
public class Program
{
    public static void Main()
    {
        Product product = new Product();

        product.Name = "Apple";
        product.Price = 3.99;

        string output = JsonConvert.SerializeObject(product, Formatting.Indented);

        // Write the json string
        Console.WriteLine(output);
    }
}

public class Product
{
    public string Name { get; set; }
    
    public double Price { get; set; }
}
```

### Expected Result

```js
{
  "Name": "Apple",
  "Price": 3.99
}
```

### Actual Result

```js
{
  "Name": "Apple",
  "Price": {}
}
```

**Comment by geoffreymcgill** [comment]
Confirmed. We will fix this immediately.

**Comment by hardhub** [comment]
I think this also can be closed?

https://github.com/bridgedotnet/Bridge/issues/3066

I guess we need to compile only JSON package... Pls correct me if I am not right...

**Comment by geoffreymcgill** [comment]
Version 1.1.0 was released, and Deck.NET has been updated. Your original sample is now working correctly. 

https://deck.net/cc50624a20455f41d38591fca347902b
