### ISSUE TITLE
KeyValuePair key is default value after deserialising

### ISSUE THREAD

**Issue by Porl91** [bridgedotnet/Bridge.Newtonsoft.Json#38]
The KeyValuePair class appears to serialise correctly (preserving keys & values), however when attempting to deserialise the same KeyValuePair the key ends up as the default value. In the below example you can see that the key `1` becomes `0` when it's deserialised. I would expect the key to be `1` after being deserialsed.

Reproduce case:
https://dev.deck.net/3dfae2b205ab422534308e9397a61f08
```cs
public class Program
{
    public static void Main()
    {
        var settings = new JsonSerializerSettings { TypeNameHandling = TypeNameHandling.Objects };
        
        var json = JsonConvert.SerializeObject(new KeyValuePair<int, string>(1, "bla1"), settings);
        
        Console.WriteLine(json);
        
        var obj = JsonConvert.DeserializeObject<KeyValuePair<int, string>>(json, settings);
        
        Console.WriteLine(obj.Key);
    }
}
```

It doesn't seem to matter whether `TypeNameHandling` has be set or not.

**Edit**
As a work around I've just created my own version of the KeyValuePair class.

**Comment by geoffreymcgill** [comment]
Hi @Porl91 

Thanks for the excellent bug report. We will should be able to get this fixed right away.
