### ISSUE TITLE
CultureInfo type serialises inconsistently with C# Newtonsoft.Json serialiser

### ISSUE THREAD

**Issue by Porl91** [bridgedotnet/Bridge.Newtonsoft.Json#43]
Serialising the **CultureInfo** type in C# land using the Newtonsoft.Json serialiser just returns as the language culture code, whereas in Bridge land it seems to serialise as a regular class object.

Bridge example:
https://deck.net/b2a8d93ef6ca719a6eada151d1273ab9

C# example:
https://dotnetfiddle.net/p8r9kv

This just means that when I send **CultureInfo** objects back from the server they need to be strings, as the Bridge deserialisation code just interprets the language culture code (in this case '**iv**') as a regular string, rather than looking at the type on the specified type.

I'd expect the serialisation code to emit the language culture code (i.e. **iv** in this case) and the deserialisation code to be able to handle these codes separately from regular class objects.

**Comment by geoffreymcgill** [comment]
Hi @Porl91 – Thanks for notifying us of this defect. We will investigate and try to fix quickly. If we fix, we should be able to include and publish in a 1.2.2 release without any delay.

**Comment by Porl91** [comment]
@geoffreymcgill That's great. :) As a workaround I'm just wrapping the language culture code on Bridge side, for the time being.

**Comment by fabriciomurta** [comment]
The fix was merged upstream, will be available in version 1.2.2.
