### ISSUE TITLE
Bridge.Test.Core NuGet Package - Unavailable

### ISSUE THREAD

**Issue by ProductiveRage** [bridgedotnet/Bridge.Newtonsoft.Json#48]
I tried to run the unit tests for this repo but was unable to make the project build because there the Bridge.Test.Core package is unavailable. I hacked something up to make it work but it would have been much better to have been able to check out the repo, build it and then run the tests straight away.

Granted, this is only a problem when the "Newtonsoft.Json.Dev.sln" solution is used instead of "Newtonsoft.Json.sln" but I wanted to make a pull request for functionality and so I wanted to run the tests to try to ensure that I didn't break anything unexpected.

**Comment by geoffreymcgill** [comment]
The Bridge Test library is now available from NuGet. 

https://www.nuget.org/packages/bridge.test

The **Newtonsoft.Json.Dev.sln** should _just work_ now.
