### ISSUE TITLE
Bad data doesn't throw an exception

### ISSUE THREAD

**Issue by dionrhys** [bridgedotnet/Bridge.Newtonsoft.Json#49]
It seems like deserializing data that doesn't match the layout of the target Type silently ignores any problems instead of throwing an exception as should be done.

Reproduce code:

https://deck.net/e0537fb790a008b762ad72e9b1ffb795

```c#
public class Program
{
    public static void Main()
    {
        var json = @"{""Member1"": ""spaghetti""}";
        var parsedObj = JsonConvert.DeserializeObject<MyClass>(json);
        Console.WriteLine(parsedObj);
    }
    
    public class MyClass
    {
        public MyClass Member1;
    }
}
```

Expected Output:
```
JsonSerializationException: Error converting value "spaghetti" to type 'Program+MyClass'. Path 'Member1', line 1, position 23.
```

Actual Output:
```
{
"Member1": null
}
```

**Comment by fabriciomurta** [comment]
Pull request #56 implemented throwing exceptions when invalid data is attempted into a deserialization. This has been merged to our integration branch and will be available in our next release, 1.2.3.
