### ISSUE TITLE
Properties should not be set during deserialisation if they've already been accounted for by constructor arguments

### ISSUE THREAD

**Issue by ProductiveRage** [bridgedotnet/Bridge.Newtonsoft.Json#50]
If I have a class that has some properties that are set by its constructor then the deserialisation process should not both trying to set those properties directly _as well_ as having them set via the constructor. If there are any properties that _aren't_ set by the constructor then these _should_ be set via property setters, though.

To illustrate, the class below has three properties; one that is set by the constructor but that also has a property setter ("Id"), one that has a property setter and that is not set by the constructor ("SomethingElse") and one that is an auto property and is set in the constructor ("Name").

When the .NET version of Json.NET deserialises to an instance of this class, it will **not** call the "Id" property setter because it has already used the "Id" value from the JSON when calling the constructor.

Not only is this an inconsistency with the .NET version of Json.NET but it will also mean that the Bridge version is doing more work than it needs to because it needs to deserialise the "Id" value twice instead of only once (and this could be expensive if it's a deep object graph, particularly if that graph contains more classes like this where properties are being deserialised twice unnecessarily).

Complete example:

```
public class Program
{
    public static void Main()
    {
        Console.WriteLine("Create..");
        var person = new Person(123, "Dan")
        {
            SomethingElse = 456
        };
        var settings = new JsonSerializerSettings
        {
            TypeNameHandling = TypeNameHandling.Objects
        };
        var json = JsonConvert.SerializeObject(person, settings);
        Console.WriteLine(json);
        Console.WriteLine("Deserialise..");
        var clone = JsonConvert.DeserializeObject<Person>(json);
    }
}

public class Person
{
    private int _id, _somethingElse;
    public Person(int id, string name)
    {
        Console.WriteLine("ctor");
        Id = id;
        Name = name;
    }
    public int Id
    {
        get { return _id; }
        set
        {
            Console.WriteLine("set_Id");
            _id = value;
        }
    }
    public int SomethingElse
    {
        get { return _somethingElse; }
        set
        {
            Console.WriteLine("set_SomethingElse");
            _somethingElse = value;
        }
    }
    public string Name { get; }
}
```

(Available here: [deck.net/0f34310c9b74eb891c06cb601971cc30](https://deck.net/0f34310c9b74eb891c06cb601971cc30)).

When run in .NET, the following output may be seen:

> Create..
> ctor
> set_Id
> set_SomethingElse
> Deserialise..
> ctor
> set_Id
> set_SomethingElse

When run as Bridge-generated JS, the following output may be seen:

> Create..
> ctor
> set_Id
> set_SomethingElse
> Deserialise..
> ctor
> set_Id
> set_Id
> set_SomethingElse

Note that the Bridge version reports "set_Id" twice while the .NET version only once.

**Comment by fabriciomurta** [comment]
Thanks for the comprehensive report, @ProductiveRage! We've fixed this issue and just merged upstream! The fix will be available in version 1.2.3!
