### ISSUE TITLE
ObjectLiteral generic class causes "T is not reflectable and cannot be serialized"

### ISSUE THREAD

**Issue by ProductiveRage** [bridgedotnet/Bridge.Newtonsoft.Json#51]
If I have a generic class that is an `[ObjectLiteral]` and its type parameter is a type that is also `[ObjectLiteral]` then serialisation fails with

> Uncaught System.InvalidOperationException: T is not reflectable and cannot be serialized.

It seems like it's trying to ensure that the type parameter is reflectable instead of checking the actual type used to fulfil that parameter.

To demonstrate:

```csharp
public class Program
{
    public static void Main()
    {
        var settings = new JsonSerializerSettings { TypeNameHandling = Newtonsoft.Json.TypeNameHandling.Objects };
        var x = new Wrapper<Person>(new Person("test"));
        Console.WriteLine(JsonConvert.SerializeObject(x, settings));
    }
}

[ObjectLiteral(ObjectCreateMode.Constructor)]
public class Person
{
    public Person(string name)
    {
        Name = name;
    }
    public string Name { get; }
}

[ObjectLiteral(ObjectCreateMode.Constructor)]
public class Wrapper<T>
{
    public Wrapper(T value)
    {
        Value = value;
    }
    public T Value { get; }
}
```

Available at deck.net/6ca6dee61278231c6145bd52d7f034ca

It doesn't happen if there is an array of these items, strangely. So if I change

```csharp
Console.WriteLine(JsonConvert.SerializeObject(x, settings));
```

to

```csharp
Console.WriteLine(JsonConvert.SerializeObject(new[] { x }. settings));
```

then it works.

It doesn't happen if the generic class is not `[ObjectLiteral]`. It still happens if the wrapped type (Person) is no longer `[ObjectLiteral]` but it _doesn't_ happen if the type `T` is a string.

**Comment by vladsch** [comment]
It is Bridge defect
https://github.com/bridgedotnet/Bridge/issues/3231

**Comment by fabriciomurta** [comment]
Bridge defect has been fixed and merged upstream so this issue can be marked as solved as well -- but beware the fix will only be available once Bridge.Newtonsoft.Json is linked against Bridge 16.5.0 or newer.
