### ISSUE TITLE
DateTime fields aren't deserialised properly on [ObjectLiteral]

### ISSUE THREAD

**Issue by ProductiveRage** [bridgedotnet/Bridge.Newtonsoft.Json#52]
I was experimenting with `[ObjectLiteral]` for deserialisation performance and it makes things a lot faster, which is great. But it doesn't work on some properties, which is less great :(

#### Example

```csharp
public class Program
{
    public static void Main()
    {
        var settings = new JsonSerializerSettings 
        { 
            TypeNameHandling = Newtonsoft.Json.TypeNameHandling.Objects 
        };
        
        var x = new Person(DateTime.Now);
        var json = JsonConvert.SerializeObject(x, settings);
        var clone = JsonConvert.DeserializeObject<Person>(json, settings);

        Console.WriteLine(clone.Value.ToShortDateString());
    }
}

[ObjectLiteral(ObjectCreateMode.Constructor)]
public class Person
{
    public Person(DateTime value)
    {
        Value = value;
    }

    public DateTime Value { get; }
}
```

Available at https://deck.net/b683ffdeeed6ed939f88a5a0113f8118

The error is:

```
n.getFullYear is not a function
```

(because I think that it has put a string value in and claimed that it's a DateTime instance).

I think that more validation is required before taking the `[ObjectLiteral]` shortcut (which is definitely worthwhile considering how fast it is!). Maybe there needs to be a recursive check for incompatible properties? And I'm not sure if there could be edge cases relating to the fact that classes can be derived from `[ObjectLiteral]` classes without being `[ObjectLiteral]` themselves (though it's not allowed the other way around).

**Comment by ProductiveRage** [comment]
Issues #53 might be related to this (or, at least, a solution to this might work as a solution to that).

**Comment by fabriciomurta** [comment]
The fix has been applied upstream (integration branch) and will be available as we release Bridge.Newtonsoft.Json 1.2.3.

**Comment by geoffreymcgill** [comment]
@ProductiveRage – Please review the following proposal for a new **ObjectLiteralRule** which could automatic deserialisation of non-primitive types, such as **DateTime**. The Type information is required for Bridge to handle these non-primitive types in an `[ObjectLiteral]` automatically. 

https://github.com/bridgedotnet/Bridge/issues/3257
