### ISSUE TITLE
Incorrect serialisation of a non-[ObjectLiteral] class that is derived from an [ObjectLiteral] class

### ISSUE THREAD

**Issue by ProductiveRage** [bridgedotnet/Bridge.Newtonsoft.Json#54]
The following code records the `Name` property of the `Employee` class as null -

https://deck.net/f4e3b86a9b687112b7b5e980540f32d6

```csharp
public class Program
{
    public static void Main()
    {
        var x = new Employee("Test", "R123");
        var json = JsonConvert.SerializeObject(x);

        Console.WriteLine(json);
    }
}

[ObjectLiteral(ObjectCreateMode.Constructor)]
public class Person
{
    public Person(string name)
    {
        Name = name;
    }

    public string Name { get; }
}

public class Employee : Person
{
    public Employee(string name, string role) : base(name)
    {
        Role = role;
    }

    public string Role { get; }
}
```

If the Person class has the `[ObjectLiteral]` attribute removed then it works. Alternatively, if the Employee class has the `[ObjectLiteral]` attribute _added_ then it also works.

Do you think that it would be possible to change the `[ObjectLiteral]` behaviour so that derived types have to have it if their base type as it? That would probably avoid a lot of complexity (and it's already enforced the other way; derived types may not have `[ObjectLiteral]` if their base types don't). I'm about to raise one more case that will relate to this..*

\* (see #55 - though I realised, when I raised that issue, that it wouldn't be enough to require that derived types of `[ObjectLiteral]` also be `[ObjectLiteral]`; I think that any types that are properties of `[ObjectLiteral]` - and any derived from those types - would _also_ have to be `[ObjectLiteral]`??).

**Comment by vladsch** [comment]
Related issue
https://github.com/bridgedotnet/Bridge/issues/3235

**Comment by fabriciomurta** [comment]
Hi!

Just run your test case with `dev` branch.
- create new ClassLibrary project on .NET Framework 4
- install Bridge.Newtonsoft.Json 1.3.0 package (bridge 16.5.0 comes in the bundle)
- Paste the code above within the `namespace` block of the `Class1.cs` file (for simplicity)
- Build
- Open `bin/Debug/Bridge/index.html` in google chrome
- Open console (F12)
Result:
```
{"Name":"Test","Role":"R123"}
```

So, `Name` is no longer null. At least as far as the test case above is concerned, Bridge 16.5.0 addresses the issue (with Newtonsoft.Json 1.3.0!).

Thanks for reporting this issue, @ProductiveRage! Your feedback is great, and the report, clear and easy to reproduce!
