### ISSUE TITLE
Nested properties that are not [ObjectLiteral] are not deserialised correctly when parent class is [ObjectLiteral]

### ISSUE THREAD

**Issue by ProductiveRage** [bridgedotnet/Bridge.Newtonsoft.Json#55]
When an `[ObjectLiteral]` class is deserialised, it is presumed that its entire object graph is also fully `[ObjectLIteral]`, which may not be the case. This means that any methods that exist on non-`[ObjectLiteral]` types that are properties of the parent `[ObjectLiteral]` type will fail when called.

To illustrate:

```csharp
public class Program
{
    public static void Main()
    {
        var source = new Person("Test", new Role("Whatever"));
        var json = JsonConvert.SerializeObject(source);
        Console.WriteLine("source.Role.GetDescription = " + source.Role.GetDescription());
        Console.WriteLine(json);

        var clone = JsonConvert.DeserializeObject<Person>(json);
        Console.WriteLine("clone.Role.GetDescription = " + clone.Role.GetDescription());
    }
}

[ObjectLiteral(ObjectCreateMode.Constructor)]
public class Person
{
    public Person(string name, Role role)
    {
        Name = name;
        Role = role;
    }

    public string Name { get; }

    public Role Role { get; }

    public string GetName()
    {
        return Name;
    }
}

public class Role
{
    public Role(string description)
    {
        Description = description;
    }

    public string Description { get; }

    public string GetDescription()
    {
    	return Description;
    }
}
```

Available at https://deck.net/9df43065120178654cd32e3d7e992728

Expected output is:

```
source.Role.GetDescription = Whatever
{"Name":"Test","Role":{"Description":"Whatever"}}
clone.Role.GetDescription = Whatever
```

but the actual output is that the first two lines work and the third one (`clone.Role.GetDescription()`) throws an exception because that method is not defined.

If the Role class is identified as `[ObjectLiteral(ObjectCreateMode.Constructor)]` then it works.

I guess that one easy way to fix this would be to require that all types that appear as properties of `[ObjectLiteral]` classes are also `[ObjectLiteral]` themselves (so, in this case, **Role** would have to be an `[ObjectLiteral]` because **Person** is an `[ObjectLiteral]`). Any type derived from **Role** (or from **Person**) would also have to be `[ObjectLiteral]`, otherwise deserialisation would fail there is derived types were present in the JSON (possibly only applies when `TypeNameHandling` is enabled). This would obviously be a change, though - potentially a breaking change. I wonder how many people would realistically be using an `[ObjectLiteral]` class that has properties (or derived types) that are _not_ `[ObjectLiteral]`..? It may not be a great risk to any existing code - that, of course, is up to you!

Another option, perhaps, would be for a post-deserialisation "fix-up" step to "hydrate" any types that are not `[ObjectLiteral`] into real instances of whatever they need to be. This would obviously be more expensive in terms of processing but it may already be necessary for some other issues (see #52 and #53).

**Comment by geoffreymcgill** [comment]
@ProductiveRage – Thanks for this report and excellent sample. We feel you original sample should work without any modifications, so we consider the current functionality as defective. We will review and fix right away.

**Comment by vladsch** [comment]
This issue is the same #52 (test sample should work after #52 PR merging)

**Comment by fabriciomurta** [comment]
Hi!

Just run your test case with `dev` branch.
- create new ClassLibrary project on .NET Framework 4
- install Bridge.Newtonsoft.Json 1.3.0 package (bridge 16.5.0 comes in the bundle)
- Paste the code above within the `namespace` block of the `Class1.cs` file (for simplicity)
- Build
- Open `bin/Debug/Bridge/index.html` in google chrome
- Open console (F12)
Result:
```
source.Role.GetDescription = Whatever
{"Name":"Test","Role":{"Description":"Whatever"}}
clone.Role.GetDescription = Whatever
```

Just as reference, this is what I get from current deck.net version (Bridge 16.4.1, NewtonSoft.Json 1.2.2):
```
source.Role.GetDescription = Whatever
{"Name":"Test","Role":{"Description":"Whatever"}}
System.Exception: TypeError: clone.Role.GetDescription is not a function
    at Function.Main (https://deck.net/RunHandler.ashx?h=1041033135:37:83)
    at https://deck.net/resources/js/bridge/bridge.min.js?16.4.1:7:38249
    at HTMLDocument.i (https://deck.net/resources/js/bridge/bridge.min.js?16.4.1:7:5175)
    at i (https://cdnjs.cloudflare.com/ajax/libs/jquery/2.2.4/jquery.min.js:2:27151)
    at Object.add [as done] (https://cdnjs.cloudflare.com/ajax/libs/jquery/2.2.4/jquery.min.js:2:27450)
    at n.fn.init.n.fn.ready (https://cdnjs.cloudflare.com/ajax/libs/jquery/2.2.4/jquery.min.js:2:29515)
    at new n.fn.init (https://cdnjs.cloudflare.com/ajax/libs/jquery/2.2.4/jquery.min.js:2:24945)
    at n (https://cdnjs.cloudflare.com/ajax/libs/jquery/2.2.4/jquery.min.js:2:405)
    at Object.ready (https://deck.net/resources/js/bridge/bridge.min.js?16.4.1:7:5238)
    at https://deck.net/resources/js/bridge/bridge.min.js?16.4.1:7:38228
```

So, as good as fixed with the merged implementations from @vladsch, it seems.
