### ISSUE TITLE
Does not support [JsonConstructor] attribute

### ISSUE THREAD

**Issue by ProductiveRage** [bridgedotnet/Bridge.Newtonsoft.Json#6]
http://www.newtonsoft.com/json/help/html/T_Newtonsoft_Json_JsonConstructorAttribute.htm

```cs
public sealed class JsonConstructorAttribute : Attribute
```
>Instructs the JsonSerializer to use the specified constructor when deserializing that object.

In .NET, the following code:
https://dotnetfiddle.net/pELXxs
https://deck.net/64a856d7812373f924e398310a380ad0
```cs
class Program
{
    static void Main(string[] args)
    {
        var x = MyOtherString.Empty.Add("abc");

        var json = JsonConvert.SerializeObject(x);
        Console.WriteLine(json);

        var cloneX = JsonConvert.DeserializeObject<MyOtherString>(json);
        Console.WriteLine(cloneX.Value);
    }
}

public class MyOtherString
{
    public static MyOtherString Empty { get; } = new MyOtherString("");
    [JsonConstructor]
    private MyOtherString(string value)
    {
        Value = value;
    }
    public string Value { get; }
    public MyOtherString Add(string value)
    {
        return new MyOtherString(Value + value);
    }
}
```

successfully serialises the instance `x` to JSON and then back out again.

However, the Bridge version of JSON.NET does not have a [JsonConstructor] attribute and so does not compile.

This is an inconsistency with the original version of the Newtonsoft library and it means that I can't (easily) support serialisation of the [Optional&lt;T&gt;](https://github.com/ProductiveRage/Bridge.Immutable/blob/master/ProductiveRage.Immutable/Optional.cs) type in my Bridge immutability library (I would like to put the `[JsonConstructor]` attribute on the private constructor).

**Comment by geoffreymcgill** [comment]
Hi @ProductiveRage – Thanks fro the feature request. 

With the current release of **Bridge.Newtonsoft.Json**, only the features listed in the [README.md](https://github.com/bridgedotnet/Bridge.Newtonsoft.Json/blob/master/README.md) are supported. 

Our goal is to be compiling the original Json.NET source code and provide close to native support for all functionality.

**Comment by geoffreymcgill** [comment]
Support for [`[JsonConstructor]`](https://github.com/bridgedotnet/Bridge.Newtonsoft.Json/blob/master/README.md#jsonconstructor-attribute) has been added to **Bridge.Newtonsoft.Json**. 

[Deck.NET](https://deck.net) has not been updated yet with this new functionality, but it will be before the **Bridge 16.0.0-rc** release.
