### ISSUE TITLE
Add [JsonIgnore] support

### ISSUE THREAD

**Issue by geoffreymcgill** [bridgedotnet/Bridge.Newtonsoft.Json#63]
Add support for the `[JsonIgnore]` attribute. 

https://www.newtonsoft.com/json/help/html/T_Newtonsoft_Json_JsonIgnoreAttribute.htm

https://deck.net/e6a5a662ee82eb06057a7a6ed95f86e5

```csharp
[ObjectLiteral]
public class Product
{
    public string Name { get; set; }
    
	[JsonIgnore]
    public DateTime ExpiryDate { get; set; }

    public double Price { get; set; }

	[JsonIgnore]
    public string[] Sizes { get; set; }
}
```

### Expected Result

```js
{
  "Name": "Apple",
  "Price": 3.99
}
```

## See Also

* https://forums.bridge.net/forum/community/help/4968-how-to-serialize-objects-correctly-in-bridge-net

**Comment by fabriciomurta** [comment]
Implementation reproduces Newtonsoft.Json to a high degree and looks good. Merged in `dev` branch, will be available in next release of this package!
