### ISSUE TITLE
DeserializeObject always throwing

### ISSUE THREAD

**Issue by PluginIO** [bridgedotnet/Bridge.Newtonsoft.Json#65]
The following code is always throwing an exception.

```csharp
namespace Viewer3D.Settings
{
    public class RendererSettings
    {
        public RendererSettings() { }
        public double Width { get; set; }
        public double Height { get; set; }
        public bool IsAntialias { get; set; }
    }
}
```

```csharp
string json = "{'Width': 800, 'Height': 600, 'IsAntialias': true }";
RendererSettings renderSettings = JsonConvert.DeserializeObject<RendererSettings>(json);
```

![capture](https://user-images.githubusercontent.com/1716106/32832725-64deb38e-c9f4-11e7-9c96-3e284c14b616.JPG)

**Comment by vladsch** [comment]
The JSON format requires double quotes and will not accept single quotes. As you see on your screenshot, the exception is thrown by native browser's JSON parser.

**Comment by PluginIO** [comment]
Ha... that was an easy fix. Had closed the page but I had lifted that from an example for this library somewhere. Anyway, working great now. Cheers!

**Comment by fabriciomurta** [comment]
It is true, Newtonsoft.Json does support single quotes in values but, as per JSON specification, it should be double quotes. Issue #80 digs a little further into this subject.

It would be nice to have the same behavior between the two libraries but, for a non-standard feature, would the performance compromised by the non-native code worth the while?
