### ISSUE TITLE
Serialised System.Uri objects $type field contains incorrect assembly name

### ISSUE THREAD

**Issue by Porl91** [bridgedotnet/Bridge.Newtonsoft.Json#67]
When serialising `System.Uri` objects within a Bridge app, the `$type` field appears to specify that it's apart of the `mscorlib` assembly rather than the `System` assembly.

Here's a repro case:
https://deck.net/25654940fc6bd4aa3f033ee8f1f7a723

`jsonFromBridge` is being serialised / deserialised within the Bridge app, meaning that it's able to serialise & deserialise properly.

`jsonFromCSharp` has comes from a C# demo app and has the assembly name `System`, causing the deserialisation to fail as it can't find `System.Uri` in the `System` assembly.

**Comment by geoffreymcgill** [comment]
Hi @Porl91 – Thanks for the report. I have reproduced the issue. We will investigate and attempt to fix right away.

**Comment by vladsch** [comment]
Fixed in https://github.com/bridgedotnet/Bridge/pull/3287

**Comment by fabriciomurta** [comment]
The necessary fix has been applied to bridge and will be available when bridge 16.5.1 is available. The Newtonsoft.Json library itself is not affected by the issue so the fix is not tied up to the next Bridge.Newtonsoft.json release, but next Bridge's release.
