### ISSUE TITLE
Custom implementation of IEnumerable<T> loses item properties after deserialisation

### ISSUE THREAD

**Issue by Porl91** [bridgedotnet/Bridge.Newtonsoft.Json#68]
This issue appears to relate to a change that was made between `Bridge.Newtonsoft.Json` version **1.2.1** and **1.3.0**

We have a custom implementation of `IEnumerable<T>` that's represented internally as a linked list. When we serialise it, it appears to retain all it's properties and the JSON looks like it did in previous versions, however when we deserialise the JSON back into an object the object doesn't have the structure we expect.

Here's an reproduce of the issue:
https://deck.net/ff78eabbfc84f2fe56032300f3804f8d

The variable **o2** in this example has the properties `names` and `value`. In `names` there's a JS array of the property names for the item, and `value` seems to be the actual item itself.

The deserialised collection does appear to have all it's items, although when I attempt to access a property of any of the items (illustrated by the .Select() call and the foreach block) the property `Name` doesn't appear to have a value.

Any ideas what could be causing this? As I mentioned, this seemed to all work fine in version **1.2.1**

**Comment by fabriciomurta** [comment]
Hi! A bug is causing this! @vladsch has already fixed it and we'll be merging the fix in real soon.

Thanks for reporting the issue!

**Comment by fabriciomurta** [comment]
Well, and just merged! It will make it to version 1.4.0 (or whatever the milestone of this issue points to, in case it changes from now).

**Comment by Porl91** [comment]
Hi @fabriciomurta That's great. Thanks! :)
