### ISSUE TITLE
(1.0-beta3) Deserialising lists that had TypeNameHandling=All results in empty list

### ISSUE THREAD

**Issue by DanTup** [bridgedotnet/Bridge.Newtonsoft.Json#7]
Given the following C# (real JSON.net) ([dotnetfiddle](https://dotnetfiddle.net/QZw5A3)):

```cs
var settings = new JsonSerializerSettings { TypeNameHandling = TypeNameHandling.All };
		
var data = new List<string> { "1", "2", "3" };
var json = JsonConvert.SerializeObject(data, settings);

Console.WriteLine(json);
```

The output is:

```js
{
  "$type":"System.Collections.Generic.List`1[[System.String, mscorlib]], mscorlib",
  "$values":["1","2","3"]
}
```

However when you try to deserialise with Bridge:

```cs
var settings = new JsonSerializerSettings { TypeNameHandling = TypeNameHandling.All };
var json = "{\"$type\":\"System.Collections.Generic.List`1[[System.String, mscorlib]], mscorlib\",\"$values\":[\"1\",\"2\",\"3\"]}";
        
Console.WriteLine(JsonConvert.DeserializeObject<List<string>>(json, settings));
```

You get back an empty list ([deck](https://deck.net/15a37ec05ea36fd582cd84c9588159ae)):

```js
[]
```

Using TypeNameHandling.Auto for the serialisation seems to work (since it serialises as an array) but presumably this should work out of the box?

**Comment by geoffreymcgill** [comment]
Currently [`TypeNameHandling.All`](https://github.com/bridgedotnet/Bridge.Newtonsoft.Json#typenamehandling) is not supported in **Bridge.Newtonsoft.Json**... but either is `Auto`, so I'm not sure why `Auto` would be giving different results. 

We will investigate.

**Comment by DanTup** [comment]
The different results are from changing the .net side (which results in json.net serialising as a standard array).

I was under the impression we'd been using TypeNameHandling for several weeks to fix an issue deserialising into types that had interfaces in their definitions? @Porl91

**Comment by DanTup** [comment]
It looks like when TypeNameHandling was originally added it was a bool:

https://github.com/bridgedotnet/Bridge/issues/2427

I believe we were setting that to `true` (which I presume is the same as `All`).

**Comment by DanTup** [comment]
Sorry, I just followed your link and saw that you support `.Objects`, which seems to resolve the issue. I guess when the `bool` was changed we assumed `All` was preserving the same behaviour, but actually it was `Objects`.

We'll switch to `Objects`, that should put us back where we were :-) (cc: @Porl91)

**Comment by geoffreymcgill** [comment]
Originally when the functionality was included in **Bridge.Json**, `TypeNameHandling` did accept just a boolean. The Json.NET API supports the same functionality, but slightly different API and types.

Glad to hear `Objects` has solved the issue.

**Comment by DanTup** [comment]
@geoffreymcgill Is it worthwhile removing the unsupported values from the enum until they're supported? A compile error/missing value would be much better than a subtle runtime issue.

**Comment by geoffreymcgill** [comment]
yes, I agree they should be removed. We will remove before the next release.

**Comment by geoffreymcgill** [comment]
Issue #9 has been created to track the removal of the unsupported [TypeNameHandling](https://github.com/bridgedotnet/Bridge.Newtonsoft.Json#typenamehandling) values.
