### ISSUE TITLE
Bridge.Html5.FormData isn't reflectable or serialisable

### ISSUE THREAD

**Issue by Porl91** [bridgedotnet/Bridge.Newtonsoft.Json#71]
Currently when attempting to serialise a **FormData** object it throws an exception relating to it not being reflectable:

`System.Exception: Uncaught System.InvalidOperationException: FormData is not reflectable and cannot be serialized.`

I'm not sure whether the **Bridge.Newtonsoft.Json** library would be able to serialise / de-serialise them if it were reflectable, as it's a JavaScript class rather than a C# type.

Here's a repro of the issue: https://deck.net/46ff934fec2feb727ffc8b33a05a14bf

Would it be possible for this type to be serialisable / reflectable? It's quite common for us to serialise **FormData** in our generic HTTP request helpers, and would mean that we don't have to have any special code to handle this case.

**Comment by vladsch** [comment]
Try to use filter
https://deck.net/f781ab07d34068b7eabdd541c1d83a63

**Comment by Porl91** [comment]
Hi @vladsch - thanks for the help, this is good to know for the future. On second thought what I'm requesting here doesn't really make sense, as if we serialise **FormData** there won't be a type to deserialise out as on the server side. 

I feel that I should be able to just adapt our HTTP request helpers to ensure that when we send POST data we avoid serialising if the type is a JavaScript class. I'll close this off now!
