### ISSUE TITLE
Support [JsonProperty]

### ISSUE THREAD

**Issue by bktv** [bridgedotnet/Bridge.Newtonsoft.Json#72]
Feature Request: Our team could use support for `[JsonProperty]` (described below)

https://www.newtonsoft.com/json/help/html/T_Newtonsoft_Json_Serialization_JsonProperty.htm

We don't need full support of every property outlined in the newtonsoft docs, but we would like to use it so private member variables of a class can be serialized.

**Comment by geoffreymcgill** [comment]
Thanks for the suggestion. We will try to add support for `[JsonProperty]` in the next day or two and include in the upcoming **1.4.0** release. 

Our plan was to release **1.4.0** today, but we feel this feature is important enough to delay the release temporarily in order to include.

**Comment by bktv** [comment]
Excellent! Thanks!

**Comment by fabriciomurta** [comment]
The fix was merged and will make it to the attached milestone (currently referring to version 1.4.0).
