### ISSUE TITLE
Custom types as Dictionary keys serialise as the string "[object Object]"

### ISSUE THREAD

**Issue by DanTup** [bridgedotnet/Bridge.Newtonsoft.Json#74]
When using custom structs as keys for a dictionary, serialisation results in `[object Object]` as the key.

Eg.:

```cs
var key = new MyKey(1);
var listingLevelNames = new Dictionary<MyKey, string> ();
listingLevelNames.Add(key, "None");

var serialisedKey = Serialise(key);
var serialisedDictionary = Serialise(listingLevelNames);

Console.WriteLine("Solo Key: " + serialisedKey);
Console.WriteLine("Dictionary: " + serialisedDictionary);
```

Outputs:

> Solo Key: {"$type":"Demo.MyKey, Demo","Value":1}
> Dictionary: {"[object Object]":"None"}

See [example on Deck](https://deck.net/ff550585cb4530707c11c5cb3936cfee/three).

**Comment by DanTup** [comment]
Actually, I'm not sure if this is actually a bug - I guess it just ToStrings the key (I think JSON.NET does the same, though I couldn't find a way to import it into DotNetFiddle). In JSON you can't have arbitrary objects as keys!

**Comment by DanTup** [comment]
Here's the output from JSON.NET in .NET:

> Solo Key: {"$type":"JsonTest.MyKey, JsonTest","Value":1}
> Dictionary: {"$type":"System.Collections.Generic.Dictionary`2[[JsonTest.MyKey, JsonTest],[System.String, mscorlib]], mscorlib","1":"None"}

Looks like it uses the `ToString()` on the key and uses that as the key in the JSON.

**Comment by fabriciomurta** [comment]
This has been merged upstream. A side issue was logged under #76, where any dictionary do not fancy the output mangled by different settings during serialization.

**Comment by fabriciomurta** [comment]
bridgedotnet/Bridge#3376 reports another way to explore this issue, whereas pull request #87 implements the fix.
