### ISSUE TITLE
SerializeObject ignores TypeNameHandling.Objects in Dictionaries

### ISSUE THREAD

**Issue by fabriciomurta** [bridgedotnet/Bridge.Newtonsoft.Json#76]
The output of `SerializeObject()` is the same regardless of the `TypeNameHandling.Objects` setting passed.

### Steps To Reproduce

https://deck.net/0b4265a54d07fce5203c36ca08d909e3

### Expected Result

Same as C# ([fiddle](https://dotnetfiddle.net/JjN180))
```
Simple: {"5":"five"}
Detailed: {"$type":"System.Collections.Generic.Dictionary`2[[System.Int32, mscorlib],[System.String, mscorlib]], mscorlib","5":"five"}
```

### Actual Result

```
Simple: {"5":"five"}
Detailed: {"5":"five"}
```

**Comment by vladsch** [comment]
Fixed already
