### ISSUE TITLE
Wrong boolean deserialization when value was string

### ISSUE THREAD

**Issue by colderlord** [bridgedotnet/Bridge.Newtonsoft.Json#79]
Here is example in Deck: https://deck.net/76509f0b3c05dfc042b5aef5ebd35304

JsonConvert.js: when deserializing object when `typeof raw === "string"`, but type `System.Boolean` strange value check: `raw !== ""`, thats why i can always send any strings and value will always `true`.
I try to fix this by `tryparse`

i was create [pull request](https://github.com/bridgedotnet/Bridge.Newtonsoft.Json/pull/78) for this issue

**Comment by geoffreymcgill** [comment]
Awesome! thanks. 

We will review the pr.

**Comment by fabriciomurta** [comment]
Thank you! The commit was just merged upstream to our integration branch! It will make it to the next release, according to the attached milestone (currently, 1.4.1).
