### ISSUE TITLE
Deserializes empty classes in IEnumerable

### ISSUE THREAD

**Issue by andersnm** [bridgedotnet/Bridge.Newtonsoft.Json#81]
Repro:
https://deck.net/07b7c57e8c7eb9e220af7c9757e1da91

Based on this test:
https://github.com/bridgedotnet/Bridge.Newtonsoft.Json/commit/0e38d6b3c919063fda6a8a8f5ae846db5dcbf88d#diff-31b46464d355f435d70c3c58dbd19bc2

The code in Deck works with Bridge.Newtonsoft.Json 1.2.1, but not 1.3.0 nor 1.4.0. Seems like constructor parameters for IEnumerable item classes are mandatory, and parameters must be named similar as the properties in the class.

Output:
```
o2: bla1
o2: bla2
d2: 
d2: 
t2: 
t2: 
```

Expected output:
```
o2: bla1
o2: bla2
d2: bla1
d2: bla2
t2: bla1
t2: bla2
```

**Comment by fabriciomurta** [comment]
Looks good!
https://dev.deck.net/07b7c57e8c7eb9e220af7c9757e1da91
(this is latest deck with just merged fix for this issue!)
