### ISSUE TITLE
TimeSpan deserialization does not work

### ISSUE THREAD

**Issue by hardhub** [bridgedotnet/Bridge.Newtonsoft.Json#89]
https://deck.net/57067763f18bfd70093f8b65dfcae5c4
https://dotnetfiddle.net/Widget/HmlufY

```C#
using System;
using Newtonsoft.Json;
					
public class Program
{
	public static void Main()
	{
		TimeSpan ts = (TimeSpan)JsonConvert.DeserializeObject("\"00:00:01\"", typeof(TimeSpan));

		Console.WriteLine(ts);
	}
}
```

```
System.Exception: uncaught exception: System.ArgumentException: Could not cast or convert from String to System.TimeSpan
ctor@https://deck.net/resources/js/bridge/bridge.min.js?16.8.0:7:88705
ctor@https://deck.net/resources/js/bridge/bridge.min.js?16.8.0:7:91585
DeserializeObject@https://deck.net/resources/js/bridge/newtonsoft.json.min.js?16.8.0:7:28103
Main@https://deck.net/RunHandler.ashx?h=-1165200509:9:72
init/</<@https://deck.net/resources/js/bridge/bridge.min.js?16.8.0:7:40146
i@https://deck.net/resources/js/bridge/bridge.min.js?16.8.0:7:5505
i@https://cdnjs.cloudflare.com/ajax/libs/jquery/2.2.4/jquery.min.js:2:27146
add@https://cdnjs.cloudflare.com/ajax/libs/jquery/2.2.4/jquery.min.js:2:27450
n.fn.ready@https://cdnjs.cloudflare.com/ajax/libs/jquery/2.2.4/jquery.min.js:2:29497
n.fn.init@https://cdnjs.cloudflare.com/ajax/libs/jquery/2.2.4/jquery.min.js:2:24943
n@https://cdnjs.cloudflare.com/ajax/libs/jquery/2.2.4/jquery.min.js:2:405
ready@https://deck.net/resources/js/bridge/bridge.min.js?16.8.0:7:5554
init/<@https://deck.net/resources/js/bridge/bridge.min.js?16.8.0:7:40122
init@https://deck.net/resources/js/bridge/bridge.min.js?16.8.0:7:40108
Bridge.assembly@https://deck.net/resources/js/bridge/bridge.min.js?16.8.0:7:40762
@https://deck.net/RunHandler.ashx?h=-1165200509:4:1

```

**Comment by FasettoAndrew** [comment]
Would the above issue be causing the issue I'm experiencing with DateTimeOffset deserialization failing with argument out of range exception for offset (which is a TimeSpan)?

https://deck.net/ba083a00c886571deec195adc6497b53

**Comment by fabriciomurta** [comment]
Hello, @FasettoAndrew!

Your deck is not triggering any exception to me. So can't say the issue is related or not to this one. As far as the original issue is concerned, it looks like removed from the recent pull request to this issue.

Please double check the deck you provided, if you can truly reproduce the issue, or have more information on how to actually reproduce it, create a new issue reporting it so we can check it out.

**Comment by FasettoAndrew** [comment]
By going to my deck.net link I still see the issue. I have included a screenshot of the deck.net page so you can see what version of bridge it is built with.

![image](https://user-images.githubusercontent.com/13521143/39565499-1b3b0ebc-4eb0-11e8-9539-79e928b4ced5.png)

**Comment by hardhub** [comment]
@FasettoAndrew 

It is different issue.

I got the following:  

`Argument_UTCOutOfRange, Parameter name: offset`

My and deck servers are most likely in different time zones.  
So create new issue as it is recommended and reference this one.
